apiversion: v1  
kind: service
metadata:
   name: backend-svc
   labels:
     app: backend-springboot
spec:
  type: nodeport
  ports:
   - port: 8080
     nodeport: 30001
     protocol: TCP
  selector:
     app: backend-springboot
